### ISSUE TITLE
Should we weight as in the benchmarking paper

### ISSUE THREAD

**Issue by zouter** [dynverse/competition#1]
Right now there is quite an imbalance towards linear datasets. We can easily precalculate the weights and include them inside https://github.com/dynverse/competition/blob/master/tc-scorer/aggregate-scores#L20

**Comment by birdofpreyru** [comment]
@zouter Sure, it is fine for me to do any weighting you say is the best. If you use dataset type as its name prefix (i.e. call input datasets somewhat like `linear.name.h5`) and tell me the weight for each type, I can update the aggregation script. Or, if we need a custom weight for each particular dataset, just generate a CSV or JSON file containing the dataset name > weight mapping, and I'll do the rest.

**Comment by rcannood** [comment]
@zouter I think this is a good idea. 

Perhaps we should specify the weight of the dataset, but also the mean and sd used in the [normal transformation](https://github.com/dynverse/dynbenchmark/blob/master/package/R/suite_benchmark_aggregate.R#L20)?

**Comment by zouter** [comment]
Thanks guys! This is almost included now :+1:
